// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/missoma-redesign/DarkMode.tsx": () => import("../components/mockups/missoma-redesign/DarkMode.tsx"),
  "./components/mockups/missoma-redesign/LightMode.tsx": () => import("../components/mockups/missoma-redesign/LightMode.tsx")
};
